<?php

namespace SmartCartBundle\Repository;

/**
 * CartProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProductRepository extends \Doctrine\ORM\EntityRepository
{
}
