<?php

namespace SmartCartBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllParentsCategory() {
        return $this->createQueryBuilder('c')
        ->andWhere('c.category IS null')
        ->getQuery()->getResult();
    }
}
