smart_cart_homepage:
    path:     /
    defaults: { _controller: SmartCartBundle:Default:index }

smart_cart_admin_user_list:
    path:     /admin/users
    defaults: { _controller: SmartCartBundle:Admin\User:index }

smart_cart_admin_user_delete:
    path:     /admin/user/{userId}/delete
    defaults: { _controller: SmartCartBundle:Admin\User:delete }
    requirements:
        userId: '\d+'

smart_cart_admin_user_create:
    path:     /admin/user/create
    defaults: { _controller: SmartCartBundle:Admin\User:create }

smart_cart_admin_user_edit:
    path:     /admin/user/{userId}
    defaults: { _controller: SmartCartBundle:Admin\User:edit }
    requirements:
        userId: '\d+'

smart_cart_admin_category_list:
    path:     /admin/categories
    defaults: { _controller: SmartCartBundle:Admin\Category:index }

smart_cart_admin_category_create:
    path:     /admin/category/create
    defaults: { _controller: SmartCartBundle:Admin\Category:create }
