smart_cart_homepage:
    path:     /
    defaults: { _controller: SmartCartBundle:Default:index }

smart_cart_admin_user_list:
    path:     /admin/users
    defaults: { _controller: SmartCartBundle:Admin\User:index }

smart_cart_admin_user_delete:
    path:     /admin/user/{userId}/delete
    defaults: { _controller: SmartCartBundle:Admin\User:delete }
    requirements:
        userId: '\d+'
