smart_cart_homepage:
    path:     /
    defaults: { _controller: SmartCartBundle:Default:index }

smart_cart_legal_mentions:
    path:     /mentions
    defaults: { _controller: SmartCartBundle:Default:legalMentions }

smart_cart_admin_user_list:
    path:     /admin/users
    defaults: { _controller: SmartCartBundle:Admin\User:index }

smart_cart_admin_user_delete:
    path:     /admin/user/{userId}/delete
    defaults: { _controller: SmartCartBundle:Admin\User:delete }
    requirements:
        userId: '\d+'

smart_cart_admin_user_create:
    path:     /admin/user/create
    defaults: { _controller: SmartCartBundle:Admin\User:create }

smart_cart_admin_user_edit:
    path:     /admin/user/{userId}
    defaults: { _controller: SmartCartBundle:Admin\User:edit }
    requirements:
        userId: '\d+'

smart_cart_admin_user_create:
    path:     /admin/user/create
    defaults: { _controller: SmartCartBundle:Admin\User:create }

smart_cart_admin_cart_create:
    path:     /admin/cart/create
    defaults: { _controller: SmartCartBundle:Admin\Cart:create }

smart_cart_admin_cart_delete:
    path:     /admin/cart/{cartId}/delete
    defaults: { _controller: SmartCartBundle:Admin\Cart:delete }
    requirements:
        userId: '\d+'

smart_cart_admin_cart_list:
    path:     /admin/carts
    defaults: { _controller: SmartCartBundle:Admin\Cart:index }

smart_cart_admin_cart_edit:
    path:     /admin/cart/{cartId}
    defaults: { _controller: SmartCartBundle:Admin\Cart:edit }
    requirements:
        cartId: '\d+'

smart_cart_admin_category_list:
    path:     /admin/categories
    defaults: { _controller: SmartCartBundle:Admin\Category:index }

smart_cart_admin_category_create:
    path:     /admin/category/create
    defaults: { _controller: SmartCartBundle:Admin\Category:create }

smart_cart_admin_category_delete:
    path:     /admin/category/{categoryId}/delete
    defaults: { _controller: SmartCartBundle:Admin\Category:delete }
    requirements:
        categoryId: '\d+'

smart_cart_admin_category_edit:
    path:     /admin/category/{categoryId}
    defaults: { _controller: SmartCartBundle:Admin\Category:edit }
    requirements:
        categoryId: '\d+'

smart_cart_product:
    path:     /cart/{cartId}
    defaults: { _controller: SmartCartBundle:Cart:index }
    requirements:
        cartId: '\d+'
